var email = "";
var pwd = "";
var smtp = ""; //If the email is gmail , else enter that smtp
var API_KEY = "********************************";
var AUTH_KEY = "***********************************";
exports.email = email;
exports.pwd = pwd;
exports.smtp = smtp;
exports.API_KEY = API_KEY;
exports.AUTH_KEY = AUTH_KEY;